# Generated by Django 3.0.4 on 2020-04-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20200208_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
