# Generated by Django 3.0.5 on 2020-04-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_author_book_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarybranch',
            options={'verbose_name_plural': 'Library Branches'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publish_year',
            new_name='publish_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='media/covers/nocover.jpg', upload_to='media/covers/books'),
        ),
    ]
