# Generated by Django 3.0.6 on 2020-05-09 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_auto_20200420_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='checkout',
            name='library_asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='lms.Book'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='library_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='lms.LibraryCard'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='since',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='until',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='media/covers/nocover.jpg', upload_to='covers/books'),
        ),
    ]
