# Generated by Django 3.0.6 on 2020-05-10 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_auto_20200510_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkouthistory',
            options={'ordering': ['-checked_out'], 'verbose_name_plural': 'Checkout History'},
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_placed', models.DateTimeField(auto_now_add=True)),
                ('library_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.Book')),
                ('library_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.LibraryCard')),
            ],
        ),
    ]
