# Generated by Django 3.0.6 on 2020-05-23 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_auto_20200510_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hold',
            options={'ordering': ['hold_placed']},
        ),
    ]
